name: GitHub Actions Workflows

on:
  push: # 메인 브랜치 push 이벤트 감지, jobs 실행
    branches:
      - main

jobs:
  deploy_job: # 1개 이상의 job을 가질 수 있고 각각의 job id를 지정
    runs-on: ubuntu-latest

    steps: # Job 안에서 특정 작업을 수행하는 가장 작은 단위
      - name: 테스트
        run: echo "This is test"

      - name: 테스트2
        run: |
          echo "this is test message first"
          echo "this is test message second"

      - name: 테스트3 GitHub Actions
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 테스트4 GitHub Actions Secret
        run: |
          echo ${{ secrets.MY_SECRETS }}

  node_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # node@20 을 사용하기 위한 node 환경 설치

      - name: 노드 테스트
        run: npm run test
