name: GitHub Actions Workflows

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 테스트
        run: echo "This is test"

      - name: 테스트2
        run: npm run test
